services:
  api:
    build: .
    ports:
      - "1001:5000"
    volumes:
        - type: bind
          source: "/Users/rikenshah/Documents/fabric database"
          target: /fd

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - api